apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fitness-platform
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml
images:
  - name: ghcr.io/your-user-or-org/api-gateway
    newTag: latest
