name: Advanced Java CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # 1. Сборка, тестирование и статический анализ
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Запускаем тесты! В хорошем CI/CD код без прохождения тестов не собирается
      - name: Build and Test with Maven
        run: mvn clean verify

      # Сканирование зависимостей (pom.xml) на уязвимости
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'